<?php
/**
 * UploadApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Uctoplus\API
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * {portal_name} API
 *
 * Production environment is located at `{portal_api_url}/production/`.  Sandbox environment is located at `{portal_api_url}/sandbox/`.  All communication with API is encoded in UTF-8. This REST API is based on Open API v3 standard. For help with implementation or access to the test environment please contact our helpdesk
 *
 * The version of the OpenAPI document: 4.2.0
 * Contact: helpdesk@{portal_domain}
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Uctoplus\API\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Uctoplus\API\ApiException;
use Uctoplus\API\Configuration;
use Uctoplus\API\FormDataProcessor;
use Uctoplus\API\HeaderSelector;
use Uctoplus\API\ObjectSerializer;

/**
 * UploadApi Class Doc Comment
 *
 * @category Class
 * @package  Uctoplus\API
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UploadApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getUploadedFile' => [
            'application/json',
        ],
        'getUploadedFiles' => [
            'application/json',
        ],
        'uploadFile' => [
            'multipart/form-data',
        ],
        'uploadedFilesIndex' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getUploadedFile
     *
     * Returning UploadedFile
     *
     * @param  \Uctoplus\API\Models\ElementType $element_type element_type (required)
     * @param  string $element_id element_id (required)
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUploadedFile'] to see the possible values for this operation
     *
     * @throws \Uctoplus\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Uctoplus\API\Models\File|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR
     */
    public function getUploadedFile($element_type, $element_id, $except = null, string $contentType = self::contentTypes['getUploadedFile'][0])
    {
        list($response) = $this->getUploadedFileWithHttpInfo($element_type, $element_id, $except, $contentType);
        return $response;
    }

    /**
     * Operation getUploadedFileWithHttpInfo
     *
     * Returning UploadedFile
     *
     * @param  \Uctoplus\API\Models\ElementType $element_type (required)
     * @param  string $element_id (required)
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUploadedFile'] to see the possible values for this operation
     *
     * @throws \Uctoplus\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Uctoplus\API\Models\File|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUploadedFileWithHttpInfo($element_type, $element_id, $except = null, string $contentType = self::contentTypes['getUploadedFile'][0])
    {
        $request = $this->getUploadedFileRequest($element_type, $element_id, $except, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\File',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 405:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Uctoplus\API\Models\File',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\File',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 405:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getUploadedFileAsync
     *
     * Returning UploadedFile
     *
     * @param  \Uctoplus\API\Models\ElementType $element_type (required)
     * @param  string $element_id (required)
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUploadedFile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUploadedFileAsync($element_type, $element_id, $except = null, string $contentType = self::contentTypes['getUploadedFile'][0])
    {
        return $this->getUploadedFileAsyncWithHttpInfo($element_type, $element_id, $except, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUploadedFileAsyncWithHttpInfo
     *
     * Returning UploadedFile
     *
     * @param  \Uctoplus\API\Models\ElementType $element_type (required)
     * @param  string $element_id (required)
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUploadedFile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUploadedFileAsyncWithHttpInfo($element_type, $element_id, $except = null, string $contentType = self::contentTypes['getUploadedFile'][0])
    {
        $returnType = '\Uctoplus\API\Models\File';
        $request = $this->getUploadedFileRequest($element_type, $element_id, $except, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUploadedFile'
     *
     * @param  \Uctoplus\API\Models\ElementType $element_type (required)
     * @param  string $element_id (required)
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUploadedFile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getUploadedFileRequest($element_type, $element_id, $except = null, string $contentType = self::contentTypes['getUploadedFile'][0])
    {

        // verify the required parameter 'element_type' is set
        if ($element_type === null || (is_array($element_type) && count($element_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $element_type when calling getUploadedFile'
            );
        }

        // verify the required parameter 'element_id' is set
        if ($element_id === null || (is_array($element_id) && count($element_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $element_id when calling getUploadedFile'
            );
        }



        $resourcePath = '/v3/upload/{elementType}/{elementId}/get';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $except,
            'except', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($element_type !== null) {
            $resourcePath = str_replace(
                '{' . 'elementType' . '}',
                ObjectSerializer::toPathValue($element_type),
                $resourcePath
            );
        }
        // path params
        if ($element_id !== null) {
            $resourcePath = str_replace(
                '{' . 'elementId' . '}',
                ObjectSerializer::toPathValue($element_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $headers['api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getUploadedFiles
     *
     * getUploadedFiles
     *
     * @param  \Uctoplus\API\Models\ElementType $element_type element_type (required)
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  int|null $offset Optional arguments for offet of items (optional, default to 0)
     * @param  int|null $limit Optional arguments limit per page (optional, default to 50)
     * @param  string|null $sort Optional arguments sort by column (optional)
     * @param  string|null $order Optional arguments order by column (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUploadedFiles'] to see the possible values for this operation
     *
     * @throws \Uctoplus\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Uctoplus\API\Models\GetUploadedFiles200Response|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR
     */
    public function getUploadedFiles($element_type, $except = null, $offset = 0, $limit = 50, $sort = null, $order = null, string $contentType = self::contentTypes['getUploadedFiles'][0])
    {
        list($response) = $this->getUploadedFilesWithHttpInfo($element_type, $except, $offset, $limit, $sort, $order, $contentType);
        return $response;
    }

    /**
     * Operation getUploadedFilesWithHttpInfo
     *
     * getUploadedFiles
     *
     * @param  \Uctoplus\API\Models\ElementType $element_type (required)
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  int|null $offset Optional arguments for offet of items (optional, default to 0)
     * @param  int|null $limit Optional arguments limit per page (optional, default to 50)
     * @param  string|null $sort Optional arguments sort by column (optional)
     * @param  string|null $order Optional arguments order by column (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUploadedFiles'] to see the possible values for this operation
     *
     * @throws \Uctoplus\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Uctoplus\API\Models\GetUploadedFiles200Response|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUploadedFilesWithHttpInfo($element_type, $except = null, $offset = 0, $limit = 50, $sort = null, $order = null, string $contentType = self::contentTypes['getUploadedFiles'][0])
    {
        $request = $this->getUploadedFilesRequest($element_type, $except, $offset, $limit, $sort, $order, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\GetUploadedFiles200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 405:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Uctoplus\API\Models\GetUploadedFiles200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\GetUploadedFiles200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 405:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getUploadedFilesAsync
     *
     * getUploadedFiles
     *
     * @param  \Uctoplus\API\Models\ElementType $element_type (required)
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  int|null $offset Optional arguments for offet of items (optional, default to 0)
     * @param  int|null $limit Optional arguments limit per page (optional, default to 50)
     * @param  string|null $sort Optional arguments sort by column (optional)
     * @param  string|null $order Optional arguments order by column (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUploadedFiles'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUploadedFilesAsync($element_type, $except = null, $offset = 0, $limit = 50, $sort = null, $order = null, string $contentType = self::contentTypes['getUploadedFiles'][0])
    {
        return $this->getUploadedFilesAsyncWithHttpInfo($element_type, $except, $offset, $limit, $sort, $order, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUploadedFilesAsyncWithHttpInfo
     *
     * getUploadedFiles
     *
     * @param  \Uctoplus\API\Models\ElementType $element_type (required)
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  int|null $offset Optional arguments for offet of items (optional, default to 0)
     * @param  int|null $limit Optional arguments limit per page (optional, default to 50)
     * @param  string|null $sort Optional arguments sort by column (optional)
     * @param  string|null $order Optional arguments order by column (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUploadedFiles'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUploadedFilesAsyncWithHttpInfo($element_type, $except = null, $offset = 0, $limit = 50, $sort = null, $order = null, string $contentType = self::contentTypes['getUploadedFiles'][0])
    {
        $returnType = '\Uctoplus\API\Models\GetUploadedFiles200Response';
        $request = $this->getUploadedFilesRequest($element_type, $except, $offset, $limit, $sort, $order, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUploadedFiles'
     *
     * @param  \Uctoplus\API\Models\ElementType $element_type (required)
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  int|null $offset Optional arguments for offet of items (optional, default to 0)
     * @param  int|null $limit Optional arguments limit per page (optional, default to 50)
     * @param  string|null $sort Optional arguments sort by column (optional)
     * @param  string|null $order Optional arguments order by column (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUploadedFiles'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getUploadedFilesRequest($element_type, $except = null, $offset = 0, $limit = 50, $sort = null, $order = null, string $contentType = self::contentTypes['getUploadedFiles'][0])
    {

        // verify the required parameter 'element_type' is set
        if ($element_type === null || (is_array($element_type) && count($element_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $element_type when calling getUploadedFiles'
            );
        }



        if ($limit !== null && $limit > 1000) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling UploadApi.getUploadedFiles, must be smaller than or equal to 1000.');
        }
        



        $resourcePath = '/v4/uploaded-files';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $element_type,
            'elementType', // param base name
            'ElementType', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $except,
            'except', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order,
            'order', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $headers['api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation uploadFile
     *
     * Uploading files over RestAPI
     *
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  \SplFileObject|null $file file (optional)
     * @param  \Uctoplus\API\Models\ElementType|null $element_type element_type (optional)
     * @param  \Uctoplus\API\Models\Attribute[]|null $attributes Additional data to fill in according (optional)
     * @param  \SplFileObject[]|null $pages Separate pages which will be glued together into one file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadFile'] to see the possible values for this operation
     *
     * @throws \Uctoplus\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Uctoplus\API\Models\UploadFile200Response|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR
     */
    public function uploadFile($except = null, $file = null, $element_type = null, $attributes = null, $pages = null, string $contentType = self::contentTypes['uploadFile'][0])
    {
        list($response) = $this->uploadFileWithHttpInfo($except, $file, $element_type, $attributes, $pages, $contentType);
        return $response;
    }

    /**
     * Operation uploadFileWithHttpInfo
     *
     * Uploading files over RestAPI
     *
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  \SplFileObject|null $file (optional)
     * @param  \Uctoplus\API\Models\ElementType|null $element_type (optional)
     * @param  \Uctoplus\API\Models\Attribute[]|null $attributes Additional data to fill in according (optional)
     * @param  \SplFileObject[]|null $pages Separate pages which will be glued together into one file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadFile'] to see the possible values for this operation
     *
     * @throws \Uctoplus\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Uctoplus\API\Models\UploadFile200Response|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR, HTTP status code, HTTP response headers (array of strings)
     */
    public function uploadFileWithHttpInfo($except = null, $file = null, $element_type = null, $attributes = null, $pages = null, string $contentType = self::contentTypes['uploadFile'][0])
    {
        $request = $this->uploadFileRequest($except, $file, $element_type, $attributes, $pages, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\UploadFile200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 405:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Uctoplus\API\Models\UploadFile200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\UploadFile200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 405:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation uploadFileAsync
     *
     * Uploading files over RestAPI
     *
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  \SplFileObject|null $file (optional)
     * @param  \Uctoplus\API\Models\ElementType|null $element_type (optional)
     * @param  \Uctoplus\API\Models\Attribute[]|null $attributes Additional data to fill in according (optional)
     * @param  \SplFileObject[]|null $pages Separate pages which will be glued together into one file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadFile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadFileAsync($except = null, $file = null, $element_type = null, $attributes = null, $pages = null, string $contentType = self::contentTypes['uploadFile'][0])
    {
        return $this->uploadFileAsyncWithHttpInfo($except, $file, $element_type, $attributes, $pages, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation uploadFileAsyncWithHttpInfo
     *
     * Uploading files over RestAPI
     *
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  \SplFileObject|null $file (optional)
     * @param  \Uctoplus\API\Models\ElementType|null $element_type (optional)
     * @param  \Uctoplus\API\Models\Attribute[]|null $attributes Additional data to fill in according (optional)
     * @param  \SplFileObject[]|null $pages Separate pages which will be glued together into one file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadFile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadFileAsyncWithHttpInfo($except = null, $file = null, $element_type = null, $attributes = null, $pages = null, string $contentType = self::contentTypes['uploadFile'][0])
    {
        $returnType = '\Uctoplus\API\Models\UploadFile200Response';
        $request = $this->uploadFileRequest($except, $file, $element_type, $attributes, $pages, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'uploadFile'
     *
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  \SplFileObject|null $file (optional)
     * @param  \Uctoplus\API\Models\ElementType|null $element_type (optional)
     * @param  \Uctoplus\API\Models\Attribute[]|null $attributes Additional data to fill in according (optional)
     * @param  \SplFileObject[]|null $pages Separate pages which will be glued together into one file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadFile'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function uploadFileRequest($except = null, $file = null, $element_type = null, $attributes = null, $pages = null, string $contentType = self::contentTypes['uploadFile'][0])
    {







        $resourcePath = '/v3/upload/add';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if (is_array($except)) {
            $except = ObjectSerializer::serializeCollection($except, 'csv');
        }
        if ($except !== null) {
            $resourcePath = str_replace(
                '{' . 'except' . '}',
                ObjectSerializer::toPathValue($except),
                $resourcePath
            );
        }

        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'file' => $file,
            'element_type' => $element_type,
            'attributes' => $attributes,
            'pages' => $pages,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $headers['api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation uploadedFilesIndex
     *
     * uploadFile
     *
     * @param  \Uctoplus\API\Models\ElementType $element_type element_type (required)
     * @param  \DateTime|null $from from (optional)
     * @param  \DateTime|null $to to (optional)
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadedFilesIndex'] to see the possible values for this operation
     *
     * @throws \Uctoplus\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Uctoplus\API\Models\File[]|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR
     */
    public function uploadedFilesIndex($element_type, $from = null, $to = null, $except = null, string $contentType = self::contentTypes['uploadedFilesIndex'][0])
    {
        list($response) = $this->uploadedFilesIndexWithHttpInfo($element_type, $from, $to, $except, $contentType);
        return $response;
    }

    /**
     * Operation uploadedFilesIndexWithHttpInfo
     *
     * uploadFile
     *
     * @param  \Uctoplus\API\Models\ElementType $element_type (required)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadedFilesIndex'] to see the possible values for this operation
     *
     * @throws \Uctoplus\API\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Uctoplus\API\Models\File[]|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR|\Uctoplus\API\Models\ResponseContentERROR, HTTP status code, HTTP response headers (array of strings)
     */
    public function uploadedFilesIndexWithHttpInfo($element_type, $from = null, $to = null, $except = null, string $contentType = self::contentTypes['uploadedFilesIndex'][0])
    {
        $request = $this->uploadedFilesIndexRequest($element_type, $from, $to, $except, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\File[]',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
                case 405:
                    return $this->handleResponseWithDataType(
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Uctoplus\API\Models\File[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\File[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 405:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Uctoplus\API\Models\ResponseContentERROR',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation uploadedFilesIndexAsync
     *
     * uploadFile
     *
     * @param  \Uctoplus\API\Models\ElementType $element_type (required)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadedFilesIndex'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadedFilesIndexAsync($element_type, $from = null, $to = null, $except = null, string $contentType = self::contentTypes['uploadedFilesIndex'][0])
    {
        return $this->uploadedFilesIndexAsyncWithHttpInfo($element_type, $from, $to, $except, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation uploadedFilesIndexAsyncWithHttpInfo
     *
     * uploadFile
     *
     * @param  \Uctoplus\API\Models\ElementType $element_type (required)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadedFilesIndex'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadedFilesIndexAsyncWithHttpInfo($element_type, $from = null, $to = null, $except = null, string $contentType = self::contentTypes['uploadedFilesIndex'][0])
    {
        $returnType = '\Uctoplus\API\Models\File[]';
        $request = $this->uploadedFilesIndexRequest($element_type, $from, $to, $except, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'uploadedFilesIndex'
     *
     * @param  \Uctoplus\API\Models\ElementType $element_type (required)
     * @param  \DateTime|null $from (optional)
     * @param  \DateTime|null $to (optional)
     * @param  \Uctoplus\API\Models\Except[]|null $except Optional arguments for exclude data from response (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['uploadedFilesIndex'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function uploadedFilesIndexRequest($element_type, $from = null, $to = null, $except = null, string $contentType = self::contentTypes['uploadedFilesIndex'][0])
    {

        // verify the required parameter 'element_type' is set
        if ($element_type === null || (is_array($element_type) && count($element_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $element_type when calling uploadedFilesIndex'
            );
        }





        $resourcePath = '/v3/upload/index';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($element_type !== null) {
            $resourcePath = str_replace(
                '{' . 'elementType' . '}',
                ObjectSerializer::toPathValue($element_type),
                $resourcePath
            );
        }
        // path params
        if ($from !== null) {
            $resourcePath = str_replace(
                '{' . 'from' . '}',
                ObjectSerializer::toPathValue($from),
                $resourcePath
            );
        }
        // path params
        if ($to !== null) {
            $resourcePath = str_replace(
                '{' . 'to' . '}',
                ObjectSerializer::toPathValue($to),
                $resourcePath
            );
        }
        // path params
        if (is_array($except)) {
            $except = ObjectSerializer::serializeCollection($except, 'csv');
        }
        if ($except !== null) {
            $resourcePath = str_replace(
                '{' . 'except' . '}',
                ObjectSerializer::toPathValue($except),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api-key');
        if ($apiKey !== null) {
            $headers['api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
