<?php
/**
 * ImportInvoiceV4RequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Uctoplus\API
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Účto+ API
 *
 * Production environment is located at `https://api.moje.uctoplus.sk/production/`.  Sandbox environment is located at `https://api.moje.uctoplus.sk/sandbox/`.  All communication with API is encoded in UTF-8. This REST API is based on Open API v3 standard. For help with implementation or access to the test environment please contact our helpdesk
 *
 * The version of the OpenAPI document: 4.3.0
 * Contact: helpdesk@uctoplus.sk
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Uctoplus\API\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ImportInvoiceV4RequestTest Class Doc Comment
 *
 * @category    Class
 * @description ImportInvoiceV4Request
 * @package     Uctoplus\API
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ImportInvoiceV4RequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ImportInvoiceV4Request"
     */
    public function testImportInvoiceV4Request()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payload"
     */
    public function testPropertyPayload()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "send_via_peppol"
     */
    public function testPropertySendViaPeppol()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "webhook"
     */
    public function testPropertyWebhook()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
