<?php
/**
 * V2ApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Uctoplus\API
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * {portal_name} API
 *
 * Production environment is located at `{portal_api_url}/production/`.  Sandbox environment is located at `{portal_api_url}/sandbox/`.  All communication with API is encoded in UTF-8. This REST API is based on Open API v3 standard. For help with implementation or access to the test environment please contact our helpdesk
 *
 * The version of the OpenAPI document: 4.1.0
 * Contact: helpdesk@{portal_domain}
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Uctoplus\API\Test\Api;

use \Uctoplus\API\Configuration;
use \Uctoplus\API\ApiException;
use \Uctoplus\API\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * V2ApiTest Class Doc Comment
 *
 * @category Class
 * @package  Uctoplus\API
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class V2ApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addAddress
     *
     * addAddress.
     *
     */
    public function testAddAddress()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAddressById
     *
     * getAddressById..
     *
     */
    public function testGetAddressById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAddressByInternalId
     *
     * getAddressByInternalId..
     *
     */
    public function testGetAddressByInternalId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAddressList
     *
     * getAddressList.
     *
     */
    public function testGetAddressList()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCountries
     *
     * getCountries.
     *
     */
    public function testGetCountries()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCurrencies
     *
     * getCurrencies.
     *
     */
    public function testGetCurrencies()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDeliveryTypes
     *
     * getDeliveryTypes.
     *
     */
    public function testGetDeliveryTypes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getInvoiceCounter
     *
     * getInvoiceCounter.
     *
     */
    public function testGetInvoiceCounter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getInvoiceCounters
     *
     * getInvoiceCounters.
     *
     */
    public function testGetInvoiceCounters()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getLogos
     *
     * getLogos.
     *
     */
    public function testGetLogos()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPaymentTypes
     *
     * getPaymentTypes.
     *
     */
    public function testGetPaymentTypes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSignatures
     *
     * getSignatures.
     *
     */
    public function testGetSignatures()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getTemplates
     *
     * getTemplates.
     *
     */
    public function testGetTemplates()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
